import{S as f,i as m}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function g(i){const t="https://pixabay.com/api/",s=`?${new URLSearchParams({key:"42207552-ba5ee995b0c9caa99df8c1b23",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0})}`,e=t+s;return fetch(e).then(r=>{if(!r.ok)throw new Error("Error fetching data");return r.json()})}const y="/goit-js-hw-11/assets/icon-close-e733eca7.svg",d={formSearch:document.querySelector(".form-search"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader")},{formSearch:a,galleryList:u,loader:l}=d,h=new f(".gallery a",{captionsData:"alt",captionDelay:250});a.addEventListener("submit",p);function p(i){i.preventDefault();const t=a.elements.query.value.trim();t!==""&&(u.innerHTML="",l.style.display="block",g(t).then(function({hits:o}){o.length>0?(L(o),a.elements.query.value="",h.refresh()):c("Sorry, there are no images matching your search query. Please try again!")}).catch(o=>{c(`Error fetching images: ${o}`)}).finally(function(){a.reset(),l.style.display="none"}))}function c(i){m.show({message:i,id:"errorMsg",iconUrl:y,iconColor:"white",timeout:4e3,position:"topRight",backgroundColor:"#ef4040",progressBarColor:"#b51b1b"})}function b({webformatURL:i,largeImageURL:t,tags:o,likes:s,views:e,comments:r,downloads:n}){return`
    <li class="gallery-item">
    <a class="gallery-link" href="${t}">
    <img class="gallery-image" src="${i}" alt="${o}" width="360"/></a>
    <ul class="gallery-img-caption">
    <li class="gallery-img-info">Likes ${s}</li>
    <li class="gallery-img-info">Views ${e}</li>
    <li class="gallery-img-info">Comments ${r}</li>
    <li class="gallery-img-info">Downloads ${n}</li>
    </ul>
    </li>`}function L(i){const t=i.map(o=>b(o)).join("");u.insertAdjacentHTML("beforeend",t)}
//# sourceMappingURL=commonHelpers.js.map
