import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();function m(s){const t="https://pixabay.com/api/",i=`?${new URLSearchParams({key:"42207552-ba5ee995b0c9caa99df8c1b23",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0})}`,e=t+i;return fetch(e).then(r=>{if(!r.ok)throw new Error("Error fetching data");return r.json()})}const f="/goit-js-hw-11/assets/icon-close-e733eca7.svg",g={formSearch:document.querySelector(".form-search"),galleryList:document.querySelector(".gallery")},{formSearch:a,galleryList:n,loader:b}=g;a.addEventListener("submit",h);n.addEventListener("click",d);function h(s){s.preventDefault();const t=a.elements.query.value.trim();if(n.innerHTML="",t!=="")return m(t).then(o=>{if(o.hits.length===0)c.error({id:"errorMsg",iconUrl:f,iconColor:"white",message:"Sorry, there are no images matching your search query. Please try again!",timeout:4e3,position:"topRight",backgroundColor:"#ef4040",progressBarColor:"#b51b1b"});else{const i=o.hits.map(e=>y(e)).join("");n.insertAdjacentHTML("beforeend",i),a.elements.query.value=""}}).catch(o=>{console.error("Error fetching images:",o)})}function d(s){s.preventDefault(),new u(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function y({webformatURL:s,largeImageURL:t,tags:o,likes:i,views:e,comments:r,downloads:l}){return`<li class="gallery-item">
    <a class="gallery-link" href="${t}">
    <img class="gallery-image" src="${s}" alt="${o}" width="360" height="300"/></a>
    <ul class="gallery-img-info">
    <li class="gallery-img-likes">Likes ${i}</li>
    <li class="gallery-img-views">Views ${e}</li>
    <li class="gallery-img-comments">Comments ${r}</li>
    <li class="gallery-img-downloads">Downloads ${l}</li>
    </ul>
    </li>`}
//# sourceMappingURL=commonHelpers.js.map
